name: Building docker image.
run-name: Building project by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  Run-with-default-args:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the
          runner."
      - run: echo "Checking environment variable"
      - name: Building the image
        run: |
          make image
